roms:
  - id: lineageos
    display_name: Lineage OS
    manifest_url: https://github.com/LineageOS/android.git
    branches:
      - lineage-21.0
      - lineage-22.2
      - lineage-23.0
      - lineage-23.1
      
  - id: derpfest
    display_name: DerpFest AOSP
    manifest_url: https://github.com/DerpFest-AOSP/android_manifest.git
    branches:
      - "16"
      
  - id: yaap
    display_name: Yet Another AOSP Project
    manifest_url: https://github.com/yaap/manifest.git
    branches:
      - sixteen
      - fifteen
      
  - id: pos
    display_name: PixelOS AOSP
    manifest_url: https://github.com/PixelOS-AOSP/android_manifest.git
    branches:
      - sixteen
      - sixteen-qpr1
      
  - id: axion
    display_name: Axion OS
    manifest_url: https://github.com/AxionAOSP/android.git
    branches:
      - lineage-23.0
      - lineage-23.1

  - id: crdroid
    display_name: crDroid
    manifest_url: https://github.com/crdroidandroid/android.git
    branches:
      - "15.0"
      - "16.0"

  - id: avium
    display_name: AviumUi
    manifest_url: https://github.com/AviumUI/android_manifests.git
    branches:
      - "avium-16"
      - "avium-16-qpr1-wip"
      
  - id: alphadroid
    display_name: Alphadroid
    manifest_url: https://github.com/AlphaDroid-Project/manifest.git
    branches:
      - "alpha-16.1"

  - id: halcyon
    display_name: Halcyon
    manifest_url: https://github.com/halcyonproject/manifest.git
    branches:
      - "16.0"
      - "16.1"

  - id: lumine
    display_name: Lumine
    manifest_url: https://github.com/LumineDroid/platform_manifest.git
    branches:
      - "bynx"

  - id: lunarisaosp
    display_name: Lunaris
    manifest_url: https://github.com/Lunaris-AOSP/android.git
    branches:
      - "16"

  - id: projectmica
    display_name: Project-Mica
    manifest_url: https://github.com/Project-Mica/manifest.git
    branches:
      - "16-qpr1"
      - "16-qpr2"

  - id: projectinfnityx
    display_name: ProjectInfinity-X
    manifest_url: https://github.com/ProjectInfinity-X/manifest.git
    branches:
      - "16"

  - id: projectmatrixx
    display_name: ProjectMatrixx
    manifest_url: https://github.com/ProjectMatrixx/android.git
    branches:
      - "16.0"

  - id: superioros
    display_name: SuperiorOS
    manifest_url: https://github.com/SuperiorOS/manifest.git
    branches:
      - "sixteen-los"    

  - id: witaqua
    display_name: WitAqua
    manifest_url: https://github.com/WitAqua/manifest.git
    branches:
      - "16.0"
      - "16.1"

  - id: cloverproject
    display_name: The Clover Project
    manifest_url: https://github.com/The-Clover-Project/manifest.git
    branches:
      - "16"
      - "16-qpr1"

  - id: statixos
    display_name: StatixOS
    manifest_url: https://github.com/StatiXOS/android_manifest.git
    branches:
      - "bp2a"

  - id: grapheneos
    display_name: GrapheneOS
    manifest_url: https://github.com/GrapheneOS/platform_manifest.git
    branches:
      - "16"
      - "16-qpr1"
      - "16-qpr2"

  - id: evolutionx
    display_name: EvolutionX
    manifest_url: https://github.com/Evolution-X/manifest.git
    branches:
      - "bka"
      - "bq1"
      - "bq2"

  - id: neoteric
    display_name: NeotericOS
    manifest_url: https://github.com/Neoteric-OS/android_manifest.git
    branches:
      - "bka"
      
  - id: twrp
    display_name: TWRP Recovery
    manifest_url: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
    branches:
      - twrp-12.1
      - twrp-14.1
    enabled: false
repo_params:
  groups: default,-mips,-darwin,-notdefault
