roms:
  - id: lineageos
    display_name: Lineage OS
    manifest_url: https://github.com/LineageOS/android.git
    branches:
      - "lineage-23.2"
      - "lineage-22.2"

  - id: derpfest
    display_name: DerpFest AOSP
    manifest_url: https://github.com/DerpFest-AOSP/android_manifest.git
    branches:
      - "16.2"
      
  - id: yaap
    display_name: Yet Another AOSP Project
    manifest_url: https://github.com/yaap/manifest.git
    branches:
      - "sixteen"
      
  - id: pos
    display_name: PixelOS AOSP
    manifest_url: https://github.com/PixelOS-AOSP/android_manifest.git
    branches:
      - "sixteen-qpr2"

  - id: grapheneos
    display_name: GrapheneOS
    manifest_url: https://github.com/GrapheneOS/platform_manifest.git
    branches:
      - "16-qpr2"
      - "15-qpr2"
      
  - id: twrp
    display_name: TWRP Recovery
    manifest_url: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
    branches:
      - "twrp-12.1"
      - "twrp-14.1"
    enabled: false

repo_params:
  groups: default,-mips,-darwin,-notdefault
